---
# tasks file for drone

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: drone

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: drone

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: drone
